"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { categories, mockQuestions, type Difficulty } from "@/data/mockQuestions";

const difficultyStyles: Record<Difficulty, string> = { Easy: "border-emerald-500/30 bg-emerald-500/10 text-emerald-400 shadow-[0_0_16px_rgba(16,185,129,0.08)]", Medium: "border-amber-500/30 bg-amber-500/10 text-amber-400 shadow-[0_0_16px_rgba(245,158,11,0.08)]", Hard: "border-rose-500/30 bg-rose-500/10 text-rose-400 shadow-[0_0_16px_rgba(244,63,94,0.08)]" };
const physical = "border border-white/[0.08] shadow-[inset_0_1px_0_rgba(255,255,255,0.1)] active:translate-y-0.5 active:shadow-inner";
const firms = [["Goldman Sachs", 42], ["Morgan Stanley", 38], ["Blackstone", 24], ["Evercore", 19]] as const;

export default function ProblemsDirectory() {
  const router = useRouter(); const searchRef = useRef<HTMLInputElement>(null);
  const [category, setCategory] = useState("All Categories"); const [difficulty, setDifficulty] = useState<"All" | Difficulty>("All"); const [search, setSearch] = useState(""); const [firm, setFirm] = useState("");
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") { event.preventDefault(); searchRef.current?.focus(); } }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, []);
  const filtered = useMemo(() => mockQuestions.filter((question) => (category === "All Categories" || question.category === category) && (difficulty === "All" || question.difficulty === difficulty) && (!firm || question.firms.includes(firm)) && (!search || `${question.title} ${question.firms.join(" ")} ${question.subTopics.join(" ")}`.toLowerCase().includes(search.toLowerCase()))), [category, difficulty, firm, search]);
  const pickRandom = () => { const pool = filtered.length ? filtered : mockQuestions; router.push(`/drill/${pool[Math.floor(Math.random() * pool.length)].id}`); };
  return <main className="min-h-screen bg-[#09090b] text-zinc-100">
    <header className="sticky top-0 z-20 border-b border-white/[0.08] bg-zinc-950/80 backdrop-blur-md"><div className="mx-auto flex h-15 max-w-[1600px] items-center gap-6 px-4 lg:px-7"><a href="/" className="flex items-center gap-2 font-mono text-sm font-bold tracking-[0.14em] text-white"><span className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_12px_rgba(52,211,153,0.9)]" />TOMBSTONE</a><nav className="hidden items-center gap-1 md:flex">{["Problems", "Interview Tracks", "Discuss", "Leaderboard"].map((item) => <button key={item} className={`rounded-md px-3 py-2 text-sm ${item === "Problems" ? "bg-white/[0.07] text-white" : "text-zinc-500 hover:text-zinc-200"}`}>{item}</button>)}</nav><div className="ml-auto hidden min-w-0 max-w-md flex-1 md:block"><label className="flex items-center gap-2 rounded-md border border-white/[0.08] bg-zinc-900/60 px-3 py-2 text-sm text-zinc-500 focus-within:border-zinc-600"><span>⌕</span><input ref={searchRef} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search questions or firms" className="min-w-0 flex-1 bg-transparent outline-none placeholder:text-zinc-600" /><kbd className="rounded border border-zinc-700 bg-zinc-800 px-1.5 py-0.5 text-[10px] text-zinc-400">Ctrl K</kbd></label></div><div className="hidden items-center gap-2 rounded-md border border-orange-400/15 bg-orange-400/[0.06] px-2.5 py-1.5 text-xs text-orange-300 lg:flex"><span>♨</span> Day 3 Streak</div><div className="grid h-8 w-8 place-items-center rounded-full bg-gradient-to-br from-emerald-400 to-cyan-500 text-xs font-bold text-zinc-950">W</div></div></header>
    <div className="mx-auto grid max-w-[1600px] lg:grid-cols-[220px_minmax(0,1fr)_250px]">
      <aside className="hidden min-h-[calc(100vh-60px)] border-r border-white/[0.08] p-4 lg:block"><p className="mb-2 px-3 text-[10px] font-bold tracking-[0.16em] text-zinc-600">EXPLORE</p>{["All Problems", "Study Plans", "Company Drill Sheets", "Saved Questions"].map((item, index) => <button key={item} className={`mb-1 flex w-full items-center gap-3 rounded-md px-3 py-2 text-left text-sm ${index === 0 ? "bg-emerald-400/10 text-emerald-300" : "text-zinc-500 hover:bg-white/[0.04] hover:text-zinc-200"}`}><span className="text-xs">{index === 0 ? "⊞" : "○"}</span>{item}</button>)}<p className="mb-2 mt-8 px-3 text-[10px] font-bold tracking-[0.16em] text-zinc-600">CURATED PACKS</p>{["Bulge Bracket Top 50", "Must-Know Paper LBOs", "Accounting Traps"].map((item) => <button key={item} className="mb-1 w-full rounded-md px-3 py-2 text-left text-sm text-zinc-500 hover:bg-white/[0.04] hover:text-zinc-200">{item}</button>)}</aside>
      <section className="min-w-0 p-4 sm:p-6"><div className="grid gap-3 md:grid-cols-3">{[["M&A", "Bulge Bracket M&A Superday Pack", "40 high-yield drills", "from-emerald-500/20"], ["LBO", "Paper LBO Crash Course", "Mental math & returns", "from-amber-500/20"], ["ACC", "Accounting Mechanics", "3-Statement Mastery", "from-cyan-500/20"]].map(([label, title, caption, color]) => <button key={label} className={`${physical} group rounded-lg bg-gradient-to-br ${color} to-[#121215] p-4 text-left transition duration-150 hover:-translate-y-[1px] hover:border-zinc-700/80`}><span className="font-mono text-[10px] tracking-widest text-zinc-500">{label}</span><p className="mt-5 text-sm font-medium text-zinc-100 group-hover:text-white">{title}</p><p className="mt-1 text-xs text-zinc-500">{caption}</p></button>)}</div>
      <div className="mt-7 flex flex-wrap gap-2">{categories.map((item) => <button key={item} onClick={() => { setCategory(item); setFirm(""); }} className={`rounded-md px-3 py-1.5 text-xs transition ${category === item ? "border border-emerald-500/30 bg-emerald-500/10 text-emerald-300 shadow-[inset_0_1px_0_rgba(255,255,255,0.1)]" : "border border-white/[0.08] bg-[#121215] text-zinc-500 hover:text-zinc-200"}`}>{item}</button>)}</div>
      <div className="mt-4 flex flex-col gap-3 border-y border-white/[0.08] py-4 sm:flex-row"><label className="flex flex-1 items-center gap-2 rounded-md border border-white/[0.08] bg-[#121215] px-3 py-2 text-sm text-zinc-500"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Filter questions" className="w-full bg-transparent outline-none placeholder:text-zinc-600" /></label><select value={difficulty} onChange={(event) => setDifficulty(event.target.value as "All" | Difficulty)} className="rounded-md border border-white/[0.08] bg-[#121215] px-3 py-2 text-sm text-zinc-300 outline-none"><option>All</option><option>Easy</option><option>Medium</option><option>Hard</option></select><button onClick={pickRandom} className={`${physical} rounded-md bg-zinc-100 px-4 py-2 text-sm font-semibold text-zinc-950 transition hover:bg-white`}>⤨ Pick Random</button></div>
      <div className="mt-3 overflow-hidden rounded-lg border border-white/[0.08] bg-[#121215]"><div className="hidden grid-cols-[28px_42px_minmax(240px,1fr)_82px_82px_minmax(140px,0.65fr)] gap-3 border-b border-white/[0.08] px-4 py-3 text-[10px] font-bold tracking-wider text-zinc-600 md:grid"><span></span><span>#</span><span>TITLE</span><span>PASS RATE</span><span>LEVEL</span><span>FIRMS</span></div>{filtered.map((question) => <button key={question.id} onClick={() => router.push(`/drill/${question.id}`)} className="grid w-full grid-cols-[28px_42px_minmax(0,1fr)_82px] items-center gap-3 border-b border-white/[0.08] px-4 py-4 text-left last:border-b-0 transition-all duration-150 hover:-translate-y-[1px] hover:border-zinc-700/80 hover:bg-zinc-800/20 active:scale-[0.99] md:grid-cols-[28px_42px_minmax(240px,1fr)_82px_82px_minmax(140px,0.65fr)]"><span className="grid h-4 w-4 place-items-center rounded-full border border-zinc-700 text-[9px] text-zinc-700">○</span><span className="font-mono text-xs text-zinc-600">{String(question.number).padStart(2, "0")}</span><span className="min-w-0"><span className="block truncate text-sm text-zinc-200">{question.title}</span><span className="mt-1 block text-xs text-zinc-600 md:hidden">{question.category}</span></span><span className="text-xs text-zinc-500">{question.passRate}</span><span className={`hidden w-fit rounded border px-2 py-1 text-xs md:block ${difficultyStyles[question.difficulty]}`}>{question.difficulty}</span><span className="hidden flex-wrap gap-1 md:flex">{question.firms.map((item) => <span key={item} className="rounded bg-zinc-800 px-1.5 py-1 text-[10px] text-zinc-400">{item}</span>)}</span></button>)}{filtered.length === 0 && <p className="px-4 py-12 text-center text-sm text-zinc-500">No drills match these filters.</p>}</div></section>
      <aside className="hidden border-l border-white/[0.08] p-4 xl:block"><div className="rounded-lg border border-white/[0.08] bg-[#121215] p-4"><div className="flex items-center justify-between"><h2 className="text-sm font-medium">Activity</h2><span className="text-xs text-zinc-600">September</span></div><div className="mt-4 grid grid-cols-7 gap-1">{Array.from({ length: 35 }, (_, index) => <span key={index} className={`h-5 rounded-sm ${[3, 10, 17, 18, 24].includes(index) ? "bg-emerald-400/70" : index === 25 ? "bg-emerald-400/30" : "bg-zinc-800"}`} />)}</div><p className="mt-3 text-xs text-zinc-600">5 drills this month</p></div><div className="mt-4 rounded-lg border border-white/[0.08] bg-[#121215] p-4"><h2 className="text-sm font-medium">Solved: <span className="text-zinc-500">0 / 10</span></h2>{(["Easy", "Medium", "Hard"] as Difficulty[]).map((item) => <div key={item} className="mt-4"><div className="mb-1 flex justify-between text-xs text-zinc-500"><span>{item}</span><span>0 / {mockQuestions.filter((q) => q.difficulty === item).length}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-zinc-800"><div className="h-full w-0 bg-emerald-400" /></div></div>)}</div><div className="mt-4 rounded-lg border border-white/[0.08] bg-[#121215] p-4"><h2 className="text-sm font-medium">Trending firms</h2><div className="mt-3 flex flex-wrap gap-2">{firms.map(([name, count]) => <button key={name} onClick={() => setFirm(firm === name ? "" : name)} className={`rounded border px-2 py-1.5 text-xs transition ${firm === name ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-300" : "border-zinc-700 bg-zinc-800 text-zinc-400 hover:text-white"}`}>{name} <span className="text-zinc-600">{count}</span></button>)}</div></div></aside>
    </div></main>;
}
