"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import AppHeader from "@/components/layout/AppHeader";
import { mockQuestions, type Difficulty } from "@/data/mockQuestions";
const styles: Record<Difficulty, string> = { Easy: "border-emerald-500/30 bg-emerald-500/10 text-emerald-400", Medium: "border-amber-500/30 bg-amber-500/10 text-amber-400", Hard: "border-rose-500/30 bg-rose-500/10 text-rose-400" };
export default function SavedPage() {
  const [savedIds, setSavedIds] = useState<string[]>([]);
  useEffect(() => { const load = () => setSavedIds(JSON.parse(window.localStorage.getItem("tombstone-saved-questions") ?? "[]") as string[]); const timer = window.setTimeout(load, 0); window.addEventListener("focus", load); return () => { window.clearTimeout(timer); window.removeEventListener("focus", load); }; }, []);
  const saved = mockQuestions.filter((question) => savedIds.includes(question.id)); const unsave = (id: string) => { const next = savedIds.filter((value) => value !== id); setSavedIds(next); window.localStorage.setItem("tombstone-saved-questions", JSON.stringify(next)); };
  return <main className="min-h-screen bg-[#121316] text-[#e5e7eb]"><AppHeader /><div className="mx-auto max-w-6xl px-5 py-10"><p className="font-mono text-xs tracking-[0.18em] text-emerald-400">REVIEW QUEUE</p><h1 className="mt-2 text-3xl font-semibold">Saved Questions</h1><p className="mt-2 text-sm text-zinc-400">Build your own last-mile review set before a Superday.</p>{saved.length === 0 ? <section className="mt-8 rounded-xl border border-[#262a34] bg-[#1c1f26] px-6 py-16 text-center"><p className="text-lg font-medium">No saved drills yet.</p><p className="mt-2 text-sm text-zinc-400">Bookmark key technical questions to review before your Superday.</p><Link href="/" className="mt-6 inline-block rounded-lg bg-emerald-400 px-4 py-2 text-sm font-semibold text-zinc-950">Explore questions</Link></section> : <div className="mt-8 overflow-hidden rounded-xl border border-[#262a34] bg-[#1c1f26]"><div className="hidden grid-cols-[minmax(240px,1fr)_90px_90px_minmax(140px,.7fr)_80px] gap-3 border-b border-[#262a34] px-5 py-3 text-[10px] tracking-wider text-zinc-500 md:grid"><span>TITLE</span><span>PASS RATE</span><span>LEVEL</span><span>FIRMS</span><span></span></div>{saved.map((question) => <div key={question.id} className="grid gap-3 border-b border-[#262a34] px-5 py-4 last:border-b-0 md:grid-cols-[minmax(240px,1fr)_90px_90px_minmax(140px,.7fr)_80px] md:items-center"><Link href={`/drill/${question.id}`} className="text-sm text-zinc-100 hover:text-emerald-300">{question.title}</Link><span className="text-xs text-zinc-500">{question.passRate}</span><span className={`w-fit rounded border px-2 py-1 text-xs ${styles[question.difficulty]}`}>{question.difficulty}</span><span className="flex flex-wrap gap-1">{question.firms.map((firm) => <span key={firm} className="rounded bg-zinc-800 px-1.5 py-1 text-[10px] text-zinc-400">{firm}</span>)}</span><button onClick={() => unsave(question.id)} className="text-left text-xs text-rose-300 hover:text-rose-200">Unsave</button></div>)}</div>}</div></main>;
}
