"use client";

import { useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import AppHeader from "@/components/layout/AppHeader";
import { createClient } from "@/lib/supabase/client";
import { mockQuestions } from "@/data/mockQuestions";
type Submission = { question_id: string; score: number; created_at: string };
export default function ProfilePage() {
  const supabase = useMemo(() => createClient(), []); const [user, setUser] = useState<User | null>(null); const [submissions, setSubmissions] = useState<Submission[]>([]);
  useEffect(() => { const { data: { subscription } } = supabase.auth.onAuthStateChange(async (_event, session) => { setUser(session?.user ?? null); if (!session?.user) { setSubmissions([]); return; } const { data } = await supabase.from("submissions").select("question_id, score, created_at").order("created_at", { ascending: false }); setSubmissions((data ?? []) as Submission[]); }); return () => subscription.unsubscribe(); }, [supabase]);
  const solved = new Set(submissions.map((item) => item.question_id)); const average = submissions.length ? Math.round(submissions.reduce((sum, item) => sum + item.score, 0) / submissions.length) : 0; const activeDates = new Set(submissions.map((item) => item.created_at.slice(0, 10))); const heatmap = Array.from({ length: 364 }, (_, index) => { const day = new Date(); day.setDate(day.getDate() - (363 - index)); return day.toISOString().slice(0, 10); }); const categories = ["Accounting & 3-Statement", "Valuation & Multiples", "LBO Modeling", "M&A / Accretion-Dilution"];
  return <main className="min-h-screen bg-[#121316] text-[#e5e7eb]"><AppHeader /><div className="mx-auto max-w-6xl px-5 py-10"><section className="rounded-xl border border-[#262a34] bg-[#1c1f26] p-6"><div className="flex flex-wrap items-center gap-5"><div className="grid h-16 w-16 place-items-center rounded-full bg-gradient-to-br from-emerald-400 to-cyan-500 text-2xl font-bold text-zinc-950">{user?.email?.[0]?.toUpperCase() ?? "A"}</div><div><h1 className="text-2xl font-semibold">{user?.email ?? "Analyst Candidate"}</h1><p className="mt-1 text-sm text-zinc-400">Investment Banking Analyst Candidate · Member since {user?.created_at ? new Date(user.created_at).toLocaleDateString(undefined, { month: "long", year: "numeric" }) : "today"}</p></div><div className="ml-auto rounded-lg border border-emerald-500/20 bg-emerald-500/10 px-4 py-3 text-center"><p className="text-2xl font-semibold text-emerald-300">{activeDates.size}</p><p className="text-xs text-zinc-400">Active days</p></div></div></section><div className="mt-6 grid gap-4 sm:grid-cols-3">{[["Solved", `${solved.size} / ${mockQuestions.length}`], ["Average score", `${average}%`], ["Practice time", `${Math.round(submissions.length * 2.5)} min`]].map(([label, value]) => <div key={label} className="rounded-xl border border-[#262a34] bg-[#1c1f26] p-5"><p className="text-sm text-zinc-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div><section className="mt-6 rounded-xl border border-[#262a34] bg-[#1c1f26] p-6"><div className="flex justify-between"><h2 className="font-semibold">Full-year activity</h2><span className="text-xs text-zinc-500">Last 52 weeks</span></div><div className="mt-5 grid grid-cols-26 gap-1 sm:grid-cols-52">{heatmap.map((day) => <span key={day} title={day} className={`aspect-square rounded-sm ${activeDates.has(day) ? "bg-emerald-400/75" : "bg-zinc-800"}`} />)}</div></section><section className="mt-6 rounded-xl border border-[#262a34] bg-[#1c1f26] p-6"><h2 className="font-semibold">Category mastery</h2><div className="mt-5 space-y-5">{categories.map((category) => { const questions = mockQuestions.filter((question) => question.category === category); const complete = questions.filter((question) => solved.has(question.id)).length; const percentage = questions.length ? Math.round((complete / questions.length) * 100) : 0; return <div key={category}><div className="mb-2 flex justify-between text-sm"><span>{category}</span><span className="text-zinc-500">{percentage}%</span></div><div className="h-2 overflow-hidden rounded bg-zinc-800"><div className="h-full bg-emerald-400" style={{ width: `${percentage}%` }} /></div></div>; })}</div></section></div></main>;
}
