create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id text not null,
  score integer not null check (score between 0 and 100),
  evaluation jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists submissions_user_created_at_idx on public.submissions (user_id, created_at desc);
create index if not exists submissions_user_question_idx on public.submissions (user_id, question_id);

alter table public.submissions enable row level security;

create policy "Users can view their own submissions" on public.submissions for select using ((select auth.uid()) = user_id);
create policy "Users can create their own submissions" on public.submissions for insert with check ((select auth.uid()) = user_id);
