"use client";
import { useState } from "react";
import type { Question } from "@/data/mockQuestions";

type Result = { score: number; summary: string; milestones: { milestone: string; status: "passed" | "partial" | "missed" }[]; commonTraps: string[] };
const badgeStyles = { Beginner: "bg-emerald-400/10 text-emerald-300", Intermediate: "bg-amber-400/10 text-amber-300", Advanced: "bg-rose-400/10 text-rose-300" };
const statusStyles = { passed: "text-emerald-300", partial: "text-amber-300", missed: "text-rose-300" };
const statusIcons = { passed: "✓", partial: "~", missed: "×" };

export default function DrillWorkspace({ question }: { question: Question }) {
  const [answer, setAnswer] = useState(""); const [result, setResult] = useState<Result | null>(null); const [isSubmitting, setIsSubmitting] = useState(false); const [error, setError] = useState("");
  const words = answer.trim() ? answer.trim().split(/\s+/).length : 0;
  async function submit() { if (!answer.trim()) { setError("Write a response before submitting."); return; } setIsSubmitting(true); setError(""); try { const response = await fetch("/api/evaluate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ questionId: question.id, userAnswer: answer }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Evaluation failed."); setResult(payload); } catch (err) { setError(err instanceof Error ? err.message : "Evaluation failed."); } finally { setIsSubmitting(false); } }
  return <div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-2"><section className="rounded-xl border border-white/10 bg-zinc-950 p-6 sm:p-8"><div className="mb-6 flex flex-wrap gap-2 text-xs"><span className="rounded border border-white/10 px-2 py-1 text-zinc-400">{question.category}</span><span className={`rounded px-2 py-1 ${badgeStyles[question.difficulty]}`}>{question.difficulty}</span></div><p className="font-mono text-xs tracking-[0.18em] text-cyan-400">INTERVIEW PROMPT</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-white">{question.title}</h1><p className="mt-7 text-lg leading-8 text-zinc-300">{question.prompt}</p><details className="mt-10 rounded-lg border border-white/10 bg-white/[0.02] p-4"><summary className="cursor-pointer text-sm font-medium text-zinc-200">Hint / Context</summary><p className="mt-3 text-sm leading-6 text-zinc-400">Structure your answer step-by-step. Interviewers are listening for the financial logic as much as the final number.</p></details></section>
  <section className="space-y-5"><div className="rounded-xl border border-white/10 bg-zinc-950 p-5 sm:p-6"><div className="mb-3 flex justify-between text-sm"><label htmlFor="answer" className="font-medium text-zinc-200">Your response</label><span className="text-zinc-500">{words} words</span></div><textarea id="answer" value={answer} onChange={(e) => setAnswer(e.target.value)} placeholder="Talk through your answer as you would in an interview..." className="min-h-65 w-full resize-y rounded-lg border border-white/10 bg-zinc-900 p-4 leading-7 text-zinc-200 outline-none placeholder:text-zinc-600 focus:border-cyan-400/70" /><div className="mt-4 flex items-center justify-between gap-4"><button onClick={() => { setAnswer(""); setResult(null); setError(""); }} className="text-sm text-zinc-400 hover:text-white">Reset</button><button onClick={submit} disabled={isSubmitting} className="rounded-lg bg-cyan-400 px-5 py-2.5 text-sm font-bold text-zinc-950 disabled:opacity-50">{isSubmitting ? "Evaluating..." : "Submit Response"}</button></div>{error && <p className="mt-3 text-sm text-rose-300">{error}</p>}</div>
  {result && <div className="rounded-xl border border-cyan-400/20 bg-cyan-400/[0.04] p-5 sm:p-6"><div className="flex items-start justify-between gap-5"><div><p className="text-sm text-cyan-300">Evaluation complete</p><p className="mt-2 text-sm leading-6 text-zinc-300">{result.summary}</p></div><div className="shrink-0 text-right"><span className="text-4xl font-semibold text-white">{result.score}%</span><p className="text-xs text-zinc-500">score</p></div></div><div className="mt-6 border-t border-white/10 pt-5"><h2 className="text-sm font-medium text-white">Milestone checklist</h2><ul className="mt-3 space-y-3">{result.milestones.map((item) => <li key={item.milestone} className="flex gap-3 text-sm"><span className={`font-bold ${statusStyles[item.status]}`}>{statusIcons[item.status]}</span><span className="text-zinc-300">{item.milestone}</span></li>)}</ul></div>{result.commonTraps.length > 0 && <p className="mt-5 text-xs leading-5 text-zinc-500">Watch for: {result.commonTraps.join(" · ")}</p>}</div>}
  </section></div>;
}
