"use client";
import { useEffect, useState } from "react";
import type { Difficulty, Question } from "@/data/mockQuestions";

type Result = { score: number; summaryFeedback: string; deliveryRating: "concise" | "balanced" | "rambling" | "too_brief"; milestones: { milestone: string; status: "passed" | "partial" | "missed"; userQuote: string | null; feedback: string }[]; trapsTriggered: string[] };
const difficultyStyles: Record<Difficulty, string> = { Easy: "border-emerald-500/30 bg-emerald-500/10 text-emerald-400", Medium: "border-amber-500/30 bg-amber-500/10 text-amber-400", Hard: "border-rose-500/30 bg-rose-500/10 text-rose-400" };
const statusStyles = { passed: "border-emerald-500/20 bg-emerald-500/10 text-emerald-300", partial: "border-amber-500/20 bg-amber-500/10 text-amber-300", missed: "border-rose-500/20 bg-rose-500/10 text-rose-300" };
const statusIcons = { passed: "✓", partial: "~", missed: "×" };

export default function DrillWorkspace({ question }: { question: Question }) {
  const [answer, setAnswer] = useState(""); const [result, setResult] = useState<Result | null>(null); const [isSubmitting, setIsSubmitting] = useState(false); const [error, setError] = useState("");
  const words = answer.trim() ? answer.trim().split(/\s+/).length : 0; const seconds = Math.max(0, Math.round((words / 130) * 60)); const speakingTime = seconds < 60 ? `${seconds}s` : `${Math.floor(seconds / 60)}m ${seconds % 60}s`;
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.ctrlKey && event.key === "Enter") { event.preventDefault(); void submit(); } }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); });
  async function submit() { if (!answer.trim() || isSubmitting) { if (!answer.trim()) setError("Write a response before submitting."); return; } setIsSubmitting(true); setError(""); try { const response = await fetch("/api/evaluate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ questionId: question.id, userAnswer: answer }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error ?? "Evaluation failed."); await new Promise((resolve) => setTimeout(resolve, 450)); setResult(payload); } catch (err) { setError(err instanceof Error ? err.message : "Evaluation failed."); } finally { setIsSubmitting(false); } }
  return <div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-2"><section className="rounded-xl border border-white/[0.08] bg-[#121215] p-6 sm:p-8"><div className="mb-6 flex flex-wrap gap-2 text-xs"><span className="rounded border border-white/[0.08] bg-zinc-900 px-2 py-1 text-zinc-400">{question.category}</span><span className={`rounded border px-2 py-1 ${difficultyStyles[question.difficulty]}`}>{question.difficulty}</span></div><p className="font-mono text-[10px] tracking-[0.18em] text-emerald-400">PROBLEM {String(question.number).padStart(2, "0")}</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-white">{question.title}</h1><p className="mt-7 text-lg leading-8 text-zinc-300">{question.prompt}</p><div className="mt-7 flex flex-wrap gap-2">{question.subTopics.map((topic) => <span key={topic} className="rounded bg-zinc-800 px-2 py-1 text-xs text-zinc-400">{topic}</span>)}</div><details className="mt-10 rounded-lg border border-white/[0.08] bg-zinc-900/60 p-4 backdrop-blur-md"><summary className="cursor-pointer text-sm font-medium text-zinc-200">Hint / Context</summary><p className="mt-3 text-sm leading-6 text-zinc-400">Structure the answer out loud. Start from the core principle, work through the mechanics, and conclude by reconciling the result.</p></details></section>
  <section className="space-y-5"><div className="rounded-xl border border-white/[0.08] bg-[#121215] p-5 sm:p-6"><div className="mb-3 flex justify-between text-sm"><label htmlFor="answer" className="font-medium text-zinc-200">Your response</label><span className="text-zinc-500">{words} words · ~{speakingTime}</span></div><textarea id="answer" value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder="Talk through your answer as you would in an interview..." className="min-h-65 w-full resize-y rounded-lg border border-white/[0.08] bg-zinc-900 p-4 leading-7 text-zinc-200 outline-none transition placeholder:text-zinc-600 focus:border-emerald-500/60 focus:ring-2 focus:ring-emerald-500/20" /><div className="mt-3 h-1 overflow-hidden rounded-full bg-zinc-800"><div className="h-full max-w-full bg-gradient-to-r from-emerald-500 to-cyan-400 transition-all" style={{ width: `${Math.min(100, (words / 150) * 100)}%` }} /></div><div className="mt-4 flex items-center justify-between gap-4"><button onClick={() => { setAnswer(""); setResult(null); setError(""); }} className="rounded px-2 py-1 text-sm text-zinc-400 transition hover:bg-zinc-800 hover:text-white active:translate-y-0.5">Reset</button><button onClick={submit} disabled={isSubmitting} className="relative overflow-hidden rounded-lg border border-emerald-300/20 bg-emerald-400 px-4 py-2.5 text-sm font-bold text-zinc-950 shadow-[inset_0_1px_0_rgba(255,255,255,0.35)] transition active:translate-y-0.5 active:shadow-inner disabled:opacity-60">{isSubmitting && <span className="absolute inset-0 animate-pulse bg-linear-to-r from-transparent via-white/40 to-transparent" />}{isSubmitting ? "Evaluating" : "Submit Response"} {!isSubmitting && <kbd className="ml-2 rounded border border-zinc-950/20 bg-zinc-950/10 px-1 py-0.5 text-[10px]">Ctrl ↵</kbd>}</button></div>{error && <p className="mt-3 text-sm text-rose-300">{error}</p>}</div>
  {result && <div className="rounded-xl border border-emerald-500/20 bg-[#121215] p-5 sm:p-6"><div className="flex items-start justify-between gap-5"><div><p className="text-sm text-emerald-300">Evaluation complete</p><p className="mt-2 text-sm leading-6 text-zinc-400">{result.summaryFeedback}</p><span className="mt-3 inline-block rounded border border-white/[0.08] bg-zinc-900 px-2 py-1 text-[10px] uppercase tracking-wider text-zinc-500">Delivery: {result.deliveryRating.replace("_", " ")}</span></div><div className="shrink-0 text-right"><span className="text-4xl font-semibold text-white">{result.score}%</span><p className="text-xs text-zinc-500">score</p></div></div><div className="mt-6 border-t border-white/[0.08] pt-5"><h2 className="text-sm font-medium text-white">Milestone checklist</h2><ul className="mt-3 space-y-2">{result.milestones.map((item, index) => <li key={item.milestone} style={{ animationDelay: `${index * 80}ms` }} className={`checklist-item rounded-md border p-3 text-sm ${statusStyles[item.status]}`}><div className="flex gap-3"><span className="font-bold">{statusIcons[item.status]}</span><span className="flex-1">{item.milestone}</span><span className="text-[10px] uppercase opacity-60">{item.status}</span></div><p className="mt-2 pl-6 text-xs leading-5 opacity-80">{item.feedback}</p>{item.userQuote && <blockquote className="mt-2 ml-6 rounded border-l-2 border-current/30 bg-black/10 px-2 py-1 text-xs italic opacity-90">“{item.userQuote}”</blockquote>}</li>)}</ul></div>{result.trapsTriggered.length > 0 && <div className="mt-5 rounded-md border border-rose-500/20 bg-rose-500/[0.06] p-3 text-xs leading-5 text-rose-100"><span className="font-medium text-rose-300">Flagged traps: </span>{result.trapsTriggered.join(" · ")}</div>}</div>}
  </section></div>;
}
