"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import type { User } from "@supabase/supabase-js";
import AppHeader from "@/components/layout/AppHeader";
import { createClient } from "@/lib/supabase/client";
const banks = ["Goldman Sachs", "Morgan Stanley", "J.P. Morgan", "Evercore", "Centerview", "Blackstone"];
export default function SettingsPage() {
  const supabase = useMemo(() => createClient(), []); const [user, setUser] = useState<User | null>(null); const [password, setPassword] = useState(""); const [notice, setNotice] = useState(""); const [selectedBanks, setSelectedBanks] = useState<string[]>([]); const [division, setDivision] = useState("Investment Banking"); const [strictness, setStrictness] = useState("Standard");
  useEffect(() => { const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => setUser(session?.user ?? null)); const load = () => { const saved = window.localStorage.getItem("tombstone-recruiting-preferences"); if (saved) { const prefs = JSON.parse(saved) as { banks?: string[]; division?: string; strictness?: string }; setSelectedBanks(prefs.banks ?? []); setDivision(prefs.division ?? "Investment Banking"); setStrictness(prefs.strictness ?? "Standard"); } }; const timer = window.setTimeout(load, 0); return () => { subscription.unsubscribe(); window.clearTimeout(timer); }; }, [supabase]);
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (password.length < 6) { setNotice("Use a password with at least 6 characters."); return; } const { error } = await supabase.auth.updateUser({ password }); setNotice(error ? error.message : "Password updated."); if (!error) setPassword(""); }
  const savePreferences = () => { window.localStorage.setItem("tombstone-recruiting-preferences", JSON.stringify({ banks: selectedBanks, division, strictness })); setNotice("Recruiting preferences saved."); };
  const toggleBank = (bank: string) => setSelectedBanks((items) => items.includes(bank) ? items.filter((item) => item !== bank) : [...items, bank]);
  return <main className="min-h-screen bg-[#121316] text-[#e5e7eb]"><AppHeader /><div className="mx-auto max-w-4xl px-5 py-10"><p className="font-mono text-xs tracking-[0.18em] text-emerald-400">ACCOUNT CONTROLS</p><h1 className="mt-2 text-3xl font-semibold">Settings</h1><div className="mt-8 space-y-6"><section className="rounded-xl border border-[#262a34] bg-[#1c1f26] p-6"><h2 className="font-semibold">Account</h2><p className="mt-4 text-sm text-zinc-500">Email</p><p className="mt-1 text-sm text-zinc-200">{user?.email ?? "Not signed in"}</p><form onSubmit={changePassword} className="mt-6 flex max-w-md gap-3"><input value={password} onChange={(event) => setPassword(event.target.value)} type="password" placeholder="New password" className="min-w-0 flex-1 rounded-lg border border-[#262a34] bg-[#121316] px-3 py-2 text-sm outline-none focus:border-emerald-500/60 focus:ring-2 focus:ring-emerald-500/20" /><button className="rounded-lg bg-emerald-400 px-4 py-2 text-sm font-semibold text-zinc-950">Update password</button></form></section><section className="rounded-xl border border-[#262a34] bg-[#1c1f26] p-6"><h2 className="font-semibold">Recruiting preferences</h2><p className="mt-2 text-sm text-zinc-400">Personalize the drills you prioritize during prep.</p><p className="mt-6 text-sm text-zinc-300">Target banks</p><div className="mt-3 flex flex-wrap gap-2">{banks.map((bank) => <button key={bank} onClick={() => toggleBank(bank)} className={`rounded border px-3 py-1.5 text-sm ${selectedBanks.includes(bank) ? "border-emerald-500/40 bg-emerald-500/10 text-emerald-300" : "border-[#262a34] bg-[#121316] text-zinc-400"}`}>{bank}</button>)}</div><label className="mt-6 block text-sm text-zinc-300">Target division<select value={division} onChange={(event) => setDivision(event.target.value)} className="mt-2 block w-full max-w-sm rounded-lg border border-[#262a34] bg-[#121316] px-3 py-2 text-sm outline-none"><option>Investment Banking</option><option>Private Equity</option><option>Corporate Finance</option></select></label><p className="mt-6 text-sm text-zinc-300">Evaluator strictness</p><div className="mt-3 grid max-w-lg grid-cols-3 gap-2">{["Supportive", "Standard", "Grumpy MD"].map((item) => <button key={item} onClick={() => setStrictness(item)} className={`rounded-lg border px-3 py-2 text-sm ${strictness === item ? "border-emerald-500/40 bg-emerald-500/10 text-emerald-300" : "border-[#262a34] bg-[#121316] text-zinc-400"}`}>{item}</button>)}</div><button onClick={savePreferences} className="mt-6 rounded-lg bg-emerald-400 px-4 py-2 text-sm font-semibold text-zinc-950">Save preferences</button></section>{notice && <p className="rounded-lg border border-emerald-500/20 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-200">{notice}</p>}</div></div></main>;
}
